linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - unparam
    - prealloc

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - tmp/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: echo-store-api

  golint:
    min-confidence: 0.8

  goconst:
    min-len: 3
    min-occurrences: 3
